### ISSUE TITLE
Font not rendering in Chrome

### ISSUE THREAD

**Issue by SmallhillCZ** [googlefonts/rubik#10]
![image](https://user-images.githubusercontent.com/1273865/29358488-80d1a102-827b-11e7-9be7-b661086e6dc7.png)

Probably not Chrome problem, as the problem is on several websites and two computers each one with different Chrome version. Other fonts also work OK.

**Comment by SmallhillCZ** [comment]
Found one website that somehow solved the problem by modifying the GoogleApis CSS: https://mobirise.com/assets4/fix/RobotoRubik.css

**Comment by harrisbones** [comment]
We have also encountered this issue, testing across multiple devices and OS's we seem to have narrowed it down to Windows 7.

Looking forward to see if anyone finds a fix before we have to update our clients sites :)

**Comment by SmallhillCZ** [comment]
One way to "fix" is to make a custom css file to load the font and use another font. Here it is done by replacing Rubik by Roboto: https://mobirise.com/assets4/fix/RobotoRubik.css. At least you dont have to change all the references to Rubik you have in your site.

**Comment by vad11** [comment]
This is not chrome problem. Explorer not work with this font.

**Comment by SmallhillCZ** [comment]
The issue seems fixed.
