### ISSUE TITLE
Change the ø and Ø

### ISSUE THREAD

**Issue by larsenwork** [googlefonts/rubik#20]
They look very odd to myself (Danish is my native language) and also asked a bunch of other designers that agreed. We never do an ø or Ø like that other than maybe some display/logo fonts 🙃

It's the equivalent of having e.g. a slanted crossbar on a `t` or something.

It would look much more in place if the slash goes from bottom left to top right corner. Also would still kinda fit the typeface I'd think.

Let me know if you accept a PR and I'll fix it. 

Cheers

**Comment by davelab6** [comment]
Good to see you again :) the issue with this family is that it's hinted
with vtt so updates aren't quite straight forward... But yes if you provide
something it can be integrated :)
