### ISSUE TITLE
Weight Axis variable font

### ISSUE THREAD

**Issue by pichotta** [googlefonts/rubik#24]
@alexeiva
Hi Alexie,

A note to let you know that we have made the outlines compatible for _Rubik_ and have generated a beta variable font in the "fea-ufo-conv" branch of the repo fork.

https://github.com/TypeNetwork/rubik/tree/fea-ufo-conv

We have used the Glyphs source data on this repo as the original masters.

Best,

Jill

: : :

Hello Phillip, Sebastia, Meir and Alexei,

The Google fonts team would love to see a variable fonts version of ‘Rubik'. They have commissioned us @TypeNetwork to work on upgrading a number of font projects to be variable fonts with a single weight axis.

In order to achieve the highest quality and most efficient long term results we will be converting the source data from Glyphs to UFO. The new source data will be generated in the RoboFont environment using fontmake and ttfautohint. There has been progress on tools to make an easy path to move between the Glyphs and Robofont environment.

During the process we will be looking to improve any errors while preserving how the font appears and renders on different platforms.

We have started by making a fork off of this git repository. The upgrade will be completed for you in the near future. When the proposed final font is approved by Google they will accept a pull request.

We hope this answers some of your questions about the process. Please let us know if you have any additional comments.

Best Regards,

Jill Pichotta
Vice President
Type Network
pichotta@typenetwork.com

**Comment by jpamental** [comment]
Hey @pichotta has there been any movement on this? I have a project where I want to use Rubik variable but there's some issues with the weight axis in Safari in the version I've found.

**Comment by pichotta** [comment]
@jpamental 
Hi Jason,

Yes, the most current version of Rubik can be found on the Type Network fork off of this repo in the 'master' branch. 
https://github.com/TypeNetwork/rubik

There you will see the latest builds of 
Rubik[wght].ttf
Rubik-Italic[wght].ttf

There are two outstanding Issues. One related to whether or not the kerns are compiling correctly. We will be investigating and resolving shortly.
