### ISSUE TITLE
Change of italic "ľ" to the correct one

### ISSUE THREAD

**Issue by StaniKub** [googlefonts/rubik#41]
Hey, the italic _ľ_ character is not correctly represented. It has a tick under the letter and not in the upper right corner. Is there a way to repair it? Thanks.

**Comment by eliheuer** [comment]
Thank you! I just checked and this is an issue. You can make a pull request fixing this, or I can if I find time, but I can't make any promises. I'm assigning myself to this issue anyway.

**Comment by StaniKub** [comment]
Sorry, I'm not fluent in fonts. Don't even know where to start with it.

**Comment by kenmcd** [comment]
> 
> 
> Hey, the italic _ľ_ character is not correctly represented. It has a tick under the letter and not in the upper right corner. Is there a way to repair it? Thanks.

It appears the fonts here in the repository have already been fixed.
So download the fonts from here.

**Comment by StaniKub** [comment]
Thanks, it's also changed in Google Fonts.
