### ISSUE TITLE
Kerning issue in bold fonts between i-n and i-s

### ISSUE THREAD

**Issue by andreialecu** [googlefonts/rubik#43]
The spacing between "i" and "n", and "i" and "s" in bolder fonts doesn't look too good:

<img width="633" alt="Screenshot 2021-10-25 at 15 48 45" src="https://user-images.githubusercontent.com/697707/138697993-e1cb9f9d-1d4e-4773-b6ca-a6eda33b7d1f.png">

Seems they're not visually consistent with everything else

Here's how it could look, which I think is improved:

<img width="664" alt="Screenshot 2021-10-25 at 15 51 24" src="https://user-images.githubusercontent.com/697707/138698400-11eb6b38-988e-4505-a829-68ff3efe1e74.png">

I'm also not a fan of the ligature between f-i, also reported in #42 - but I guess that's subjective.

**Comment by RosaWagner** [comment]
Indeed there was a problem with kerning exeptions. This is fixed and it will be live in GF in few weeks.
