### ISSUE TITLE
Hataf Hebrew diacritics are broken

### ISSUE THREAD

**Issue by eliheuer** [googlefonts/rubik#49]
`hatafsegol-hb, U+05B1` should look something like this: 

<img width="291" alt="Hataf-Segol" src="https://user-images.githubusercontent.com/5162664/191409712-c1b5e3a5-a976-4c34-9902-050e68f7edd8.png">

But in the file `Rubik.glyphs` the dots are overlapping creating a blob that displays an incorrect shape on the Google Fonts site:

<img width="258" alt="Hataf-Segol-Bad" src="https://user-images.githubusercontent.com/5162664/191410195-67ff653d-6bc6-4189-8565-a03402a9ec14.png">

The same problem exists for all Hataf Hebrew diacritics, `hatafsegol-hb` `hatafpatah-hb` `hatafqamats-hb` in both the regular and italic styles.

This issue was first reported in the Google Fonts Project Template repo: https://github.com/googlefonts/googlefonts-project-template/issues/85

**Comment by RosaWagner** [comment]
Thanks Eli, I hope I fixed it correctly.
